# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Critical Otter Studies
email: reis@otter.institute
description: > # this means to ignore newlines until "baseurl:"
  Hae paradoxa illi,
  admirabilia dicamus
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://reis.space" # the base hostname & protocol for your site
twitter_username: ReisAgainst
#github_username:  jekyll

# Google services
google_analytics: UA-82255461-1

# Build settings
markdown: kramdown
